version: v1
volumes:
  lammps-data-volume:
    name: lammps-data-volume
    reference: volume://user/ephemeral
    ingress:
      - source:
          uri: https://www.lammps.org/inputs/in.lj.txt
        destination:
          uri: file://in.lj.txt
    egress:
      - source:
          uri: file://log.lammps
        destination:
          uri:
          secret:
jobs:
  run-lammps:
    image:
      uri: docker://nvcr.io/hpc/lammps:29Sep2021
    env:
      - LAMMPS_INPUT_FILE_PATH=/data/in.lj.txt
    command:
      - /bin/sh
      - '-c'
      - >-
        lmp -k on g 1 -sf kk -pk kokkos cuda/aware on neigh full comm device binsize 2.8 -var x 8 -var y 4 -var z 8
        -in ${LAMMPS_INPUT_FILE_PATH}
    cwd: /data
    resource:
      cpu:
        cores: 2
        affinity: NUMA
      memory:
        size: 14GiB
      devices:
        nvidia.com/gpu: 1
    mounts:
      lammps-data-volume:
        location: /data
