version: v1
jobs:
  hello-world:
    image:
      uri: docker://alpine:latest
    command: ['/bin/sh', '-c', 'echo "Hello, world! Hostname ${HOSTNAME}']
    resource:
      cpu:
        cores: 1
        affinity: NUMA
      memory:
        size: 1GB
